micronaut:
  application:
    name: micronautguide
# Required for pre TestResources 1.1
#test-resources:
#  containers:
#    mongodb:
#      image-name: mongo:5
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"